ALTER TABLE "MoodImage"
  ADD COLUMN IF NOT EXISTS "publicId" TEXT,
  ADD COLUMN IF NOT EXISTS "url" TEXT,
  ADD COLUMN IF NOT EXISTS "resourceType" TEXT,
  ADD COLUMN IF NOT EXISTS "size" INTEGER,
  ALTER COLUMN "data" DROP NOT NULL;
